server:
  port: 8081

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ayushstwt
    password: bgwl wnbz nzxz cpgo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true